services:
  db:
    image: postgres:15-alpine
    container_name: literasiku_db
    restart: always
    env_file:
      - ./server/.env
    environment:
      TZ: Asia/Jakarta
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - literasiku-net

  go-api:
    image: golang:1.25-alpine
    container_name: literasiku_go_api_dev
    working_dir: /app
    volumes:
      - ./server:/app
    command: sh -c "go install github.com/air-verse/air@latest && air -c .air.toml"
    env_file:
      - ./server/.env
    environment:
      APP_ENV: development
    ports:
      - "8080:8080"
    depends_on:
      - db
    networks:
      - literasiku-net

  nuxt-web:
    image: node:22-bookworm-slim
    container_name: literasiku_nuxt_dev
    working_dir: /app
    volumes:
      - ./client:/app
    command: sh -c "yarn install && yarn dev --host 0.0.0.0"
    env_file:
      - ./client/.env
    ports:
      - "3000:3000"
    depends_on:
      - go-api
    networks:
      - literasiku-net

volumes:
  pgdata:

networks:
  literasiku-net:
    driver: bridge