services:
  db:
    image: postgres:15-alpine
    container_name: literasiku_db
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER:-postgres}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-rahasia123}
      POSTGRES_DB: ${DB_NAME:-literasiku_db}
      TZ: ${DB_TIMEZONE:-Asia/Jakarta}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - literasiku-net

  go-api:
    image: golang:1.25-alpine
    container_name: server
    working_dir: /app
    volumes:
      - ./server:/app 
    command: sh -c "go install github.com/air-verse/air@latest && air -c .air.toml"
    environment:
      PORT: 8080
      APP_ENV: development
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: ${DB_USER:-postgres}
      DB_PASSWORD: ${DB_PASSWORD:-rahasia123}
      DB_NAME: ${DB_NAME:-literasiku_db}
      DB_SSLMODE: disable
      DB_TIMEZONE: Asia/Jakarta
      JWT_SECRET: ${JWT_SECRET:-super_secret_jwt_key_here}
    ports:
      - "8080:8080"
    depends_on:
      - db
    networks:
      - literasiku-net

  nuxt-web:
    image: node:22-slim
    container_name: client
    user: "1000:1000"
    working_dir: /app
    volumes:
      - ./client:/app
    command: sh -c "yarn install && yarn dev -o"
    environment:
      PORT: 3000
      HOST: 0.0.0.0
      NUXT_GO_API_BASE_URL: http://go-api:8080
      NUXT_GO_INTERNAL_API_KEY: ${NUXT_GO_INTERNAL_API_KEY:-kunci_rahasia_internal}
    ports:
      - "3000:3000"
    depends_on:
      - go-api
    networks:
      - literasiku-net

volumes:
  pgdata:

networks:
  literasiku-net:
    driver: bridge